//INCIDENT MANAGEMENT SYSTEM
IMS_ROOT_FOLDER = '0BznCgmES9uzJVnlmLXpzV2x4Vzg';
IMS_INCIDENT_LOG_SHEET_ID = '1Z-KVGp2_OB6oi2fl0G9Ni-djEKU_9d5-tUMENh7SpUQ';
IMS_DROPDOWN_VALUES_SHEET_ID ='1wdKjW7QCBN2JdzTe1DXXyHeoS4n_vzF5CKRgi_FYjN0';

//INCIDENT FOLDER TEMPLATES
IMS_TEMPLATES_FOLDER = '0BznCgmES9uzJbVQxOW1NUWozRW8';

IMS_TEMPLATES_INCIDENT_LOG_ID = '1g3CJBOr_6lqmQ7Xl5sD3PSf9gL7eQqouaXjP2MttGfU';
IMS_TEMPLATES_MEMBER_DATA_ID = '1yEn-yQjLbft4eo8ruHA8jqFkWWrc1Ft43_VSSzNwczo';
IMS_TEMPLATES_ASSET_DATA_ID = '1QlJfYWe6UvaAmEALM8d8ydrsvh66KoFenObs9NaivNE';
IMS_TEMPLATES_SITUATION_DATA_ID = '1Q3cGCo4c9sES6z24vDDIgWvJQQqtRsE8rJTVB5V5g8E';
IMS_TEMPLATES_EXPENSE_DATA_ID = '1Ee9ZZ0Ctwtfl5Xkr7gGYlA7syapC2paluO5YsnRfXKw';


//INCIDENT REPORT TEMPLATES
IMS_TEMPLATES_ASSIGNMENT_REPORT_ID = '1-iMgqg8MlO-pUc98I_3PzrWF2WVEZSqGs9lsV4WA-iw';
IMS_TEMPLATES_COVER_REPORT_ID = '1bTGmlrcxLM_AiM3cpCZrRt00JY9SuJnCHI7EBUZ2LC0';
IMS_TEMPLATES_SYNOPSIS_REPORT_ID ='16BstSjUJZlPWR2xJCG3GlJY56ykVyIqzOOFac6_bmWc'; 
IMS_TEMPLATES_MAP_REPORT_ID ='1Eq8_tnLEvOq1pDhzEKKvWcnlqs1qeKaZBeqNGiKxv94'; 
IMS_TEMPLATES_ROSTER_REPORT_ID ='1KDyh7TkReU3UKyVVbcamGmBBJRILwsFSd7xO8zdOv-c'; 
IMS_TEMPLATES_INCIDENT_LOG_REPORT_ID ='1r2krpFXv5NYCP1I3CRVgnetoE14gLnORXqc9eu_RBDw'; 
IMS_TEMPLATES_EVENT_LOG_REPORT_ID ='1mF26LUR0wx_S2E7cvSMLBbZnqQ2cRhiGW16z5hETOW8'; 
IMS_TEMPLATES_FINANCE_REPORT_ID = '1fgK5y7yhLBVFg8rfJfWzh7SKnFhjjl_YwsDLZ9Rto7g';
IMS_TEMPLATES_PACKAGE_ID = '19XVhcq1rg0wDqmtytemrMi5Nub-JYzrmTNp54_6Klv0';



//MEMBER ROSTER
MEMBER_ROSTER_SHEET_ID = '1iyFmLy4jXW01UjA3-wLJAJD_dSma1cPRKjAfGI243sQ';

//SITUATION DISPLAY
SITUATION_MAPPER_ID = '1xivQB5sUoiNDZtMJDfXFg1BO0fqL2Q6WY-bbvM83Yv4';

//API
IMS_API_MAPS_KEY = 'API KEY HERE';

//SYSTEM REPORT RECIPIENTS
IMS_ACCOUNT_REPORT_RECIPIENTS = 'taichan@ketchikanrescue.org, contact@ketchikanrescue.org';
